### ISSUE TITLE
Error message after termination SmartAntHill process on Windows

### ISSUE THREAD

**Issue by valeros** [smartanthill/smartanthill2_0#17]
pyWin32 error:

```
Unhandled Error
        Traceback (most recent call last):
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, args, *kw)
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 393, in callback
            self._startRunCallbacks(result)
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, args, *kw)
          File "e:\projects\smartanthill2_0\smartanthill\network\commstack.py", line 59, in _on_stop
            self._process.signalProcess("KILL")
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 255, in signalProcess
            win32process.TerminateProcess(self.hProcess, 1)
        pywintypes.error: (5, 'TerminateProcess', '\xce\xf2\xea\xe0\xe7\xe0\xed\xee \xe2 \xe4\xee\xf1\xf2\xf3\xef\xe5.')
```

**Comment by dmytrokyrychuk** [comment]
`\xce\xf2\xea\xe0\xe7\xe0\xed\xee \xe2 \xe4\xee\xf1\xf2\xf3\xef\xe5.` is `Отказано в доступе.` in cp1251, which means `Access denied.`.

**Comment by dmytrokyrychuk** [comment]
@valeros, can you attach the log of what happens after you terminate SmartAnthill?

**Comment by valeros** [comment]
I'm working as the admin, but this error occurs sometimes.
I will attach the full log when this error occurs next time.

**Comment by valeros** [comment]
```
2015-08-05 14:19:35+0300 [-] Received SIGINT, shutting down.
2015-08-05 14:19:35+0300 [CommStackClientProtocol,client] Stopping factory <smartanthill.network.commstack.CommStackClientFactory instance at 0x0416CCB0>
2015-08-05 14:19:35+0300 [litemq] Unregistered consumer with exchange=network and queue=network.commstack.client.200.in
2015-08-05 14:19:35+0300 [litemq] Unregistered consumer with exchange=network and queue=network.commstack.client.200.out
2015-08-05 14:19:35+0300 [sas#debug] Going to shutdown with subservices ['NetworkService', 'DeviceService', 'DashboardService', 'APIService', 'LiteMQService']
2015-08-05 14:19:35+0300 [network#debug] Going to shutdown with subservices ['TCPClient', 'DataLinkService', 'CommStackServerService']
2015-08-05 14:19:35+0300 [network.datalink.200#debug] Going to shutdown with subservices []
2015-08-05 14:19:35+0300 [network.commstack.server.200#debug] Going to shutdown with subservices []
2015-08-05 14:19:35+0300 [device#debug] Going to shutdown with subservices []
2015-08-05 14:19:35+0300 [dashboard#debug] Going to shutdown with subservices ['TCPServer']
2015-08-05 14:19:35+0300 [api#debug] Going to shutdown with subservices ['APIRestService', 'APITCPSocketService', 'APIWebSocketService']
2015-08-05 14:19:35+0300 [api.rest#debug] Going to shutdown with subservices ['TCPServer']
2015-08-05 14:19:35+0300 [api.socket#debug] Going to shutdown with subservices ['TCPServer']
2015-08-05 14:19:35+0300 [api.websocket#debug] Going to shutdown with subservices ['TCPServer']
2015-08-05 14:19:35+0300 [litemq#debug] Going to shutdown with subservices []
2015-08-05 14:19:35+0300 [-] (TCP Port 8138 Closed)
2015-08-05 14:19:35+0300 [-] Stopping factory <smartanthill.dashboard.service.DashboardSiteFactory instance at 0x04155D50>
2015-08-05 14:19:35+0300 [-] (TCP Port 8131 Closed)
2015-08-05 14:19:35+0300 [-] Stopping factory <smartanthill.api.rest.RESTSiteFactory instance at 0x04155788>
2015-08-05 14:19:35+0300 [-] (TCP Port 8133 Closed)
2015-08-05 14:19:35+0300 [-] Stopping factory <smartanthill.api.protocol.jsonrpc.JSONRPCAPIFactory instance at 0x04155580>
2015-08-05 14:19:35+0300 [sas#debug] Shutting down...
2015-08-05 14:19:35+0300 [network#debug] Shutting down...
2015-08-05 14:19:35+0300 [network.datalink.200#debug] Shutting down...
2015-08-05 14:19:35+0300 [network.datalink.200] Service has been stopped
2015-08-05 14:19:35+0300 [network.commstack.server.200#debug] Shutting down...
2015-08-05 14:19:35+0300 [network.commstack.server.200] Service has been stopped
2015-08-05 14:19:35+0300 [-] Unhandled error in Deferred:
2015-08-05 14:19:35+0300 [-] Unhandled Error
        Traceback (most recent call last):
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 393, in callback
            self._startRunCallbacks(result)
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 501, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "e:\projects\smartanthill2_0\smartanthill\network\commstack.py", line 59, in _on_stop
            self._process.signalProcess("KILL")
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 255, in signalProcess
            win32process.TerminateProcess(self.hProcess, 1)
        pywintypes.error: (5, 'TerminateProcess', '\xce\xf2\xea\xe0\xe7\xe0\xed\xee \xe2 \xe4\xee\xf1\xf2\xf3\xef\xe5.')

2015-08-05 14:19:35+0300 [network] Service has been stopped
2015-08-05 14:19:35+0300 [litemq] Unregistered consumer with exchange=network and queue=commstack.server
2015-08-05 14:19:35+0300 [litemq] Undeclared exchange 'network'
2015-08-05 14:19:35+0300 [device#debug] Shutting down...
2015-08-05 14:19:35+0300 [device] Service has been stopped
2015-08-05 14:19:35+0300 [dashboard#debug] Shutting down...
2015-08-05 14:19:35+0300 [dashboard] Service has been stopped
2015-08-05 14:19:35+0300 [api#debug] Shutting down...
2015-08-05 14:19:35+0300 [api.rest#debug] Shutting down...
2015-08-05 14:19:35+0300 [api.rest] Service has been stopped
2015-08-05 14:19:35+0300 [api.socket#debug] Shutting down...
2015-08-05 14:19:35+0300 [api.socket] Service has been stopped
2015-08-05 14:19:35+0300 [api.websocket#debug] Shutting down...
2015-08-05 14:19:35+0300 [-] (TCP Port 8132 Closed)
2015-08-05 14:19:35+0300 [-] Stopping factory <smartanthill.api.protocol.jsonrpc.JSONRPCAPIFactory instance at 0x0414A3F0>
2015-08-05 14:19:35+0300 [-] Stopping factory <txws.WebSocketFactory instance at 0x0414A990>
2015-08-05 14:19:35+0300 [api.websocket] Service has been stopped
2015-08-05 14:19:35+0300 [api] Service has been stopped
2015-08-05 14:19:35+0300 [litemq#debug] Shutting down...
2015-08-05 14:19:35+0300 [litemq] Service has been stopped
2015-08-05 14:19:35+0300 [sas] Service has been stopped
2015-08-05 14:19:35+0300 [-] Main loop terminated.
2015-08-05 14:19:35+0300 [-] Server Shut Down.
2015-08-05 14:19:35+0300 [-] Main loop terminated.
2015-08-05 14:19:35+0300 [-] Server Shut Down.
```
