### ISSUE TITLE
Error message after editing Body Parts list

### ISSUE THREAD

**Issue by valeros** [smartanthill/smartanthill2_0#19]
```
        Traceback (most recent call last):
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\web\http.py", line 823, in requestReceived
            self.process()
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\web\server.py", line 189, in process
            self.render(resrc)
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\web\server.py", line 238, in render
            body = resrc.render(self)
          File "e:\projects\smartanthill2_0\smartanthill\api\rest.py", line 82, in render
            action, request_key, data)
        --- <exception caught here> ---
          File "E:\Projects\smartanthill2_0\.tox\develop\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "e:\projects\smartanthill2_0\smartanthill\api\service.py", line 78, in request
            raise APIUnknownRequest(action.name, key)
        smartanthill.exception.APIUnknownRequest: Unknown 'EXECUTE' action with key 'device.200.Blinky'
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/smartanthill/smartanthill2_0/commit/98b6b5447db1883192d570d72be7dfd273926654
